-- AlterTable
ALTER TABLE "UserOTPCode" ADD COLUMN     "CompanyId" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "UserId" SET DEFAULT 0;

-- AddForeignKey
ALTER TABLE "UserOTPCode" ADD CONSTRAINT "UserOTPCode_CompanyId_fkey" FOREIGN KEY ("CompanyId") REFERENCES "CompanyUser"("Id") ON DELETE RESTRICT ON UPDATE CASCADE;
