import trendBizHeroBg from '../../../../../../assets/trendBizHeroBg.png';

export const style = {
    trendBizBackground: {
        height: '557px',
        background: 'rgba(0, 0, 0, 0.4)',
        borderRadius: '30px',
        background: `url(${trendBizHeroBg})`,
        backgroundRepeat: 'no-repeat',
        backgroundPosition: 'center',
        backgroundSize: 'cover',
        margin: 'auto',
        mt: 12,
        width: '95%',
        position: 'relative',
    },
    circleDown: {
        display: 'flex',
        justifyContent: 'center',
        background: '#FFFFFF',
        boxShadow: '0px 0px 40px rgba(0, 0, 0, 0.1)',
        borderRadius: '15px',
        width: '7%',
        height: '12%',
        position: 'absolute',
        right: '50%',
        bottom: -30,
    },
    heroPhone: {
        position: 'absolute',
        bottom: '-6px',
        right: '87px',
    },
    leftContainer: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-around',
        alignItems: 'flex-start',
        width: '50%',
        height: '100%',
        ml: 10,
    },
    typography1: {
        fontFamily: 'Roboto',
        fontStyle: 'normal',
        fontWeight: 800,
        fontSize: '70px',
        lineHeight: '100%',
        color: '#FFFFFF',
    },
    typography2: {
        fontFamily: 'Roboto',
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '20px',
        lineHeight: '150%',
        color: '#F2F8FF',
    },
    button:{
        width: '150%',
        fontWeight: '600',
        fontSize: '15px',
        lineHeight: '200%',
        color: ' #FFFFFF',
        boxShadow: 'none',
        textTransform: 'capitalize',
        '&:hover': {
            backgroundColor: '#F65936',
        },
        margin: 'auto',
    }
};
