export enum ForbiddenExceptionType {
    FORBIDDEN = 'FORBIDDEN',
    EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
}

export enum UnauthorizedExceptionType {
    UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
    NO_AUTHORIZATION_TOKEN = 'NO_AUTHORIZATION_TOKEN',
    USER_NOT_REGISTERED = 'USER_NOT_REGISTERED',
    NO_USER_ROLE = 'USER_HAS_NO_ROLE',
}

export enum BadRequestExceptionType {
    BAD_REQUEST = 'BAD_REQUEST',
    MISSING_FILE_TYPE = 'MISSING_FILE_TYPE',
    MISSING_FILE = 'MISSING_FILE',
}

export enum AlreadyExistsExceptionType {
    ALREADY_EXISTS = 'ALREADY_EXISTS',
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS',
    NOT_EXIST = 'EMAIL_NOT_EXIST',
}

export enum TokenExceptionType {
    EXPIRED_TOKEN = 'UNAUTHORIZED_ACCESS',
}

export enum VerifyCodeExceptionType {
    NOT_VERIFIED = 'ACCOUNT_NOT_VERIFIED',
    VERIFIED = 'ACCOUNT_ALREADY_VERIFIED',
    CODE_NOT_FOUND = 'OTP_CODE_NOT_FOUND',
}

export enum NotFoundExceptionType {
    NOT_FOUND = 'NOT_FOUND',
}
